# Generated by Django 5.0.6 on 2024-07-16 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_transactions_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
